#!/usr/bin/env python3


import ruamel.yaml
import subprocess
import sys
import os
import numpy as np
import math
import socket
import time
from netCDF4 import Dataset



work_dir = os.path.dirname(os.path.realpath(__file__))
yaml = ruamel.yaml.YAML()

yaml_stream = open(sys.argv[1], "r")
config = yaml.load(yaml_stream)
yaml_stream.close()

tmp_path = config["properties"]["tmp_path"]
result_file = config["properties"]["output_path"] + "/output.nc"
N_par = int(config["parameters"]["Nfibs"])
gamma_result = abs(float(config["parameters"]["gamma"]))
L = abs(float(config["parameters"]["L"]))

matrix_const = np.diagflat(np.ones(N_par-1),1) + np.diagflat(np.ones(N_par-1),-1)


def fun(fun_param, fun_x):
    return np.matmul(matrix_const, fun_x) + L * np.power(fun_x, 3) - fun_param * fun_x


def iterate_fun(iter_par, iter_x):
    iter_matr = matrix_const + 3.0 * L * np.diagflat(np.power(iter_x, 2), 0) - \
                iter_par * np.eye(N_par)
    return iter_x - np.matmul(np.linalg.inv(iter_matr), fun(iter_par, iter_x))


def init_fun(num, init_param):
    param_tmp = np.sqrt(2 * init_param )
    return 1.0*param_tmp / (np.sqrt(L) * np.cosh((num - int(N_par / 2)) * param_tmp))


gamma = 5.0
init_x = np.fromfunction(init_fun, (N_par,), dtype=float, init_param=gamma)

while True:
    while True:
        tmp_x = iterate_fun(gamma, init_x)
        delta_x = np.max(np.abs(init_x - tmp_x)) / np.max(init_x)
        init_x = tmp_x
        if delta_x < 1e-5 and np.max(np.abs(fun(gamma, init_x))) < 1e-5:
            break
    if gamma == gamma_result:
        break
    
    if abs(gamma - gamma_result) < 0.1:
        gamma = gamma_result
    else:
        gamma += 0.1* math.copysign(1, gamma_result - gamma)


def make_matrix(m_init, gam):
    N = len(m_init)
    def alph(n):
        return n
    def norm(n,m):
        return N + n * N + m
    def anom(n,m):
        return N + N * N + n * N + m
    t_dim = N + 2 * N * N
    result = np.zeros((t_dim, t_dim,), dtype= np.float64)
    for ind in range(N):
        result[alph(ind), alph(ind)] += -gam + 3 * m_init[alph(ind)] * m_init[alph(ind)]  
        result[alph(ind), norm(ind, ind)] += 2 * m_init[alph(ind)]
        result[alph(ind), anom(ind, ind)] += m_init[alph(ind)]
        if ind != 0:
            result[alph(ind), alph(ind - 1)] += 1.0
        if ind != N - 1:
            result[alph(ind), alph(ind + 1)] += 1.0
        
    for ind1 in range(N):
        for ind2 in range(N):
            if ind1 != 0:
                result[norm(ind1, ind2), norm(ind1 - 1, ind2)] += -1.0
            if ind1 != N -1:
                result[norm(ind1, ind2), norm(ind1 + 1, ind2)] += -1.0
            if ind2 != 0:
                result[norm(ind1, ind2), norm(ind1, ind2 - 1)] += 1.0
            if ind2 != N -1:
                result[norm(ind1, ind2), norm(ind1, ind2 + 1)] += 1.0
                
            result[norm(ind1, ind2), norm(ind1, ind2)] += 2.0 * (m_init[alph(ind2)] * m_init[alph(ind2)] - m_init[alph(ind1)] * m_init[alph(ind1)] )
            result[norm(ind1, ind2), anom(ind1, ind2)] += 1.0 * (m_init[alph(ind2)] * m_init[alph(ind2)] - m_init[alph(ind1)] * m_init[alph(ind1)] )
    
    for ind1 in range(N):
        for ind2 in range(N):
            if ind1 != 0:
                result[anom(ind1, ind2), anom(ind1 - 1, ind2)] += 1.0
            if ind1 != N -1:
                result[anom(ind1, ind2), anom(ind1 + 1, ind2)] += 1.0
            if ind2 != 0:
                result[anom(ind1, ind2), anom(ind1, ind2 - 1)] += 1.0
            if ind2 != N -1:
                result[anom(ind1, ind2), anom(ind1, ind2 + 1)] += 1.0
                
            result[anom(ind1, ind2), anom(ind1, ind2)] += 2.0 * (m_init[alph(ind2)] * m_init[alph(ind2)] + m_init[alph(ind1)] * m_init[alph(ind1)] ) - 2 * gam
            result[anom(ind1, ind2), norm(ind1, ind2)] += 1.0 * (m_init[alph(ind2)] * m_init[alph(ind2)] + m_init[alph(ind1)] * m_init[alph(ind1)] )
    
    return result

def make_vec(m_init):
    N = len(m_init)
    def alph(n):
        return n
    def norm(n,m):
        return N + n * N + m
    def anom(n,m):
        return N + N * N + n * N + m
    t_dim = N + 2 * N * N
    result = np.zeros((t_dim, ), dtype= np.float64)
    for ind in range(N):
        result[anom(ind,ind)] += - m_init[alph(ind)] * m_init[alph(ind)]
    
    return result

dim = N_par + 2 * N_par * N_par
cur_x = np.zeros((dim,), dtype = np.float64)
cur_x[:N_par] = init_x * np.sqrt(L)
matr = make_matrix(init_x * np.sqrt(L), gamma)
vec = L * make_vec(init_x * np.sqrt(L))
cur_x += np.linalg.solve(matr, vec)
#print(cur_x[:N_par])
#for ind in range( 2 * N_par):
#    print(cur_x[((ind + 1) * N_par):((ind + 2) * N_par)])

#exit()
def calc_loop(m_tmp_path):
    global cur_x
    coe = 0.01
    SOCKET_FILE = m_tmp_path + '/socket'
    if os.path.exists(SOCKET_FILE):
        os.remove(SOCKET_FILE)
    proc = subprocess.Popen([work_dir+"/CalcProj_c++", m_tmp_path + "/config.yaml"])
    
    while not os.path.exists(SOCKET_FILE):
        time.sleep(1)
    client = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    client.connect(SOCKET_FILE)
    old_x = cur_x
    old_grad = None
    for ind in range(10000):
        cur_x.tofile(m_tmp_path + "/init.bin")
        client.send('asdf'.encode('utf-8'))
        data = client.recv(1)
        rootgrp = Dataset(m_tmp_path + "/tmp.nc", "r", format="NETCDF4")
        func_vec = np.array(rootgrp.variables['vector'])
        grad_matrix = np.array(rootgrp.variables['matrix'])
        rootgrp.close()
        if np.max(np.abs(func_vec)) < 2e-9:
            break
        if ind %100 == 0:
            print(np.max(np.abs(func_vec)))
        
        if (ind + 1)%100 == 110:
            cur_x += 2.0 * np.linalg.solve(grad_matrix.T, -func_vec)
        else:
            tmp_matr = grad_matrix * np.outer(np.ones((len(func_vec),)), func_vec)
            tmp_vec = np.sum(tmp_matr, axis = 1)
            if old_grad is not None:
                delt_x = cur_x - old_x
                delt_grad = tmp_vec - old_grad
                coe = np.abs(np.inner(delt_x, delt_grad) )/ np.inner(delt_grad,delt_grad)
            
            old_x = cur_x.copy()
            old_grad = tmp_vec.copy()
            
            #print("coe : " + str(coe))
            if math.isnan(coe):
                raise RuntimeError("we have went to NaNs. ")
            cur_x -= coe * tmp_vec
            
            
        #cur_x += 0.1 * np.linalg.solve(grad_matrix.T, -func_vec)
        #cur_x -= np.matmul(np.linalg.inv(grad_matrix.T), func_vec)
    print(np.max(np.abs(func_vec)))
    print(cur_x[:N_par])
    client.send('exit'.encode('utf-8'))
    client.close()
    proc.wait()

calc_count = 73
L_array = np.zeros((calc_count), dtype = np.float64)
res = np.zeros((calc_count, dim), dtype = np.float64)

for ind in range(calc_count):
    config["parameters"]["L"] = L
    with open(tmp_path + "/config.yaml", "w") as outfile:
            yaml.dump(config, outfile)

    print("start calculating L = {0}".format(L))
    sys.stdout.flush()
    calc_loop(tmp_path)
    L_array[ind] = L
    res[ind, :] = cur_x
    L *= 1.1

ncdf = Dataset(result_file, "w", format="NETCDF4")
nc_dim0 = ncdf.createDimension('IL_count', calc_count)
nc_dim1 = ncdf.createDimension('Ifibs_count', dim)
L_nc = ncdf.createVariable('L', 'f8', ('IL_count'))
res_nc = ncdf.createVariable('I', 'f8', ('IL_count', 'Ifibs_count'))
L_nc[:] = L_array
res_nc[:] = res
ncdf.close()

